CREATE TABLE IF NOT EXISTS USER
(
  ID           BIGINT      NOT NULL AUTO_INCREMENT PRIMARY KEY,
  FIRST_NAME   VARCHAR(50) NOT NULL,
  LAST_NAME    VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS COUNTRY
(
  ID                  BIGINT      NOT NULL AUTO_INCREMENT PRIMARY KEY,
  NAME                VARCHAR(50) NOT NULL,
  LANGUAGE            VARCHAR(50) NOT NULL,
  DISCRIMINATOR       VARCHAR(50) NOT NULL,
  PHONE_CODE          INT,
  IS_POLAR_NIGHT      BOOLEAN,
  HOTTEST_MONTH       VARCHAR(12),
  AVERAGE_TEMPERATURE DOUBLE
);

CREATE TABLE IF NOT EXISTS CITY
(
  ID         BIGINT      NOT NULL AUTO_INCREMENT PRIMARY KEY,
  COUNTRY_ID BIGINT      NOT NULL,
  NAME       VARCHAR(50) NOT NULL,
  POPULATION INT         NOT NULL,
  IS_CAPITAL BOOLEAN     NOT NULL,

  FOREIGN KEY (COUNTRY_ID) references COUNTRY (ID)
);

CREATE TABLE IF NOT EXISTS ORDER_TAB
(
  ID         BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  USER_ID    BIGINT NOT NULL,
  COUNTRY_ID BIGINT NOT NULL,
  CITY_ID    BIGINT NOT NULL,
  PRICE      INT,

  FOREIGN KEY (USER_ID) references USER (ID),
  FOREIGN KEY (COUNTRY_ID) references COUNTRY (ID),
  FOREIGN KEY (CITY_ID) references CITY (ID)
);


